### ISSUE TITLE
What kind of url_types are there?

### ISSUE THREAD

**Issue by skasberger** [ScholCommLab/fhe-collector#12]
What types of url will be created?

* PMC??
* PM??
* DOI??
* DOI Old??

**Comment by Bubblbu** [comment]
- new recommended DOI pattern
- the old DOI pattern
- pmid
- pmcid
- internal publication URL from OJS (@jalperin is this correct?)
- unpaywall for other OA locations (@jalperin, I think this might be important as more and more people are actually using unpaywall as the default for OA papers)

I guess that's it for now?

**Comment by Bubblbu** [comment]
What about sci-hub links? I guess it's not feasible as a long-term solution with domains constantly changing, but that would be pretty cool. (would love to see the sharing stats for sci-hub links in general)

**Comment by skasberger** [comment]
More Infos at https://github.com/ScholCommLab/fhe-collector/wiki
