### ISSUE TITLE
Must DOIs be validated

### ISSUE THREAD

**Issue by skasberger** [ScholCommLab/fhe-collector#13]
Must a DOI be validated, before it is stored in the database for URL creation?

What kind of validations must be done? Regex?

**Comment by Bubblbu** [comment]
I would say that a quick and simple DOI validation and normalization might be good to have. Zotero has plugins that do that so I am assuming that there should be openly available solutions already.

But I don't think this is high priority as we should assume that publishers using the software should also have decent control over their DOIs in their databases

**Comment by skasberger** [comment]
Will do DOI validation with Regex.
