### ISSUE TITLE
What kinf of URL sources are there?

### ISSUE THREAD

**Issue by skasberger** [ScholCommLab/fhe-collector#14]
What types of url sources/origins are there?
* NCBI??
* doi??
* file import? are they maybe of another already mentioned origin?
* api import: do you want this feature?

**Comment by Bubblbu** [comment]
The input data will basically consist of a list of DOIs and relevant metadata.

For now that will be the only relevant import

**Comment by skasberger** [comment]
More Infos here: https://github.com/ScholCommLab/fhe-collector/wiki
