### ISSUE TITLE
Get DOI for Repo

### ISSUE THREAD

**Issue by skasberger** [ScholCommLab/fhe-collector#2]
Please check out a DOI for this repo via the ScholCom Lab Account in Zenodo. You can read more about this [here](https://github.com/OpenScienceMOOC/Module-5-Open-Research-Software-and-Open-Source/blob/master/content_development/Task_2.md).

**Comment by skasberger** [comment]
Naming of Service should be resolved first: https://github.com/ScholCommLab/fhe-collector/issues/5

**Comment by jalperin** [comment]
Let's not rush to publish the repo on Zenodo. Once we have tested and are happy with the code, then we should definitely do this.

**Comment by skasberger** [comment]
Definitely. I just wanted to start the process, but as I see, the DOI is always connected to a version. So for 1.0, the tested, deployed, documented and running first version we then will create a doi I would say.
