### ISSUE TITLE
Update Graph API version to the most current supported one

### ISSUE THREAD

**Issue by Bubblbu** [ScholCommLab/fhe-collector#24]
2.10 has been deprecated last week.

While we could go all the way up to 5.0 for the URL endpoint, that one is not supported by the Python package we use. For now, I'd suggest to simply use the newest one supported by `facebook-sdk` which is 3.3

Long term, it might actually be easier to simply drop the wrapper and use `requests` as we are only relying on a single, pretty simple endpoint anyways.

**Comment by skasberger** [comment]
I have updated to 3.1, cause thats the latest supported by `facebook-sdk`. 

Next to the request itself, it is also getting the access token and opening the graphapi.

@Bubblbu Do you know, what the difference between 3.1 and 5 is? Is it relevant for us?

**Comment by skasberger** [comment]
As I see on the facebook api page, it runs out on 27th of October.

**Comment by Bubblbu** [comment]
I'll look into that! But I'm assuming that the URL node endpoint that we use will still be the same.
