### ISSUE TITLE
Better name for the repository/service

### ISSUE THREAD

**Issue by Bubblbu** [ScholCommLab/fhe-collector#5]
should we try to come up with an actual name for the service before assigning DOIs etc (maybe Zenodo doesn't care about changing the name of the repo, but I'm not sure)

suggestions @jalperin?

facebook-ojs-ced-agent would be accurate but also very clunky :D which parts to remove...

**Comment by jalperin** [comment]
We could do without the -ojs-part at least. 

Does CED call this kind of things agents? `facebook-ced-agent` or `fb-ced-agent`. 

You're right that we need something better.

**Comment by Bubblbu** [comment]
"Every Source usually has one or more Agents dedicated to it. Each Agent connects to its Source and produces Events. The kind of data that the Source makes available, and the way that the Agent processes it, vary." from the [guide](https://www.eventdata.crossref.org/guide/sources/how-agents-work/)

`facebook-ced-agent` sounds reasonable

**Comment by skasberger** [comment]
I would suggest to name it something which is easy to remember and special. Maybe you can define a category, which then will be used for future versions or software (just like most used female names in north africa, and then pick out the better sounding ones; or second biggest cities of countries; or favourite jazz musicians family names). the category makes it easy to look for something and creates a personal connection, and the good sounding and short wording makes it easy to call and remember.

**Comment by Bubblbu** [comment]
that might actually be a nice idea... it's really hard to make the name meaningful without sacrificing legibility and brevity.

I guess we can keep this an open question...
