### ISSUE TITLE
Create agreggated metrics?

### ISSUE THREAD

**Issue by skasberger** [ScholCommLab/fhe-collector#8]
Should there be any metrics  aggregated coming from the facebook requests or should there be made any snapshot of the metrics at any given point of time?

**Comment by Bubblbu** [comment]
The tool should simply push the reported number of shares at a given point in time to CED. Data aggregation or reports over time are then available through CED (i.e., Paperbuzz in this case)

**Comment by jalperin** [comment]
what @Bubblbu said.

**Comment by skasberger** [comment]
need to document this.
